
site_name: FusionInsight MRS 生态地图
repo_name: 'fusioninsight/ecosystem'
repo_url: 'https://github.com/fusioninsight/ecosystem/tree/zh-hans'

theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'Indigo'
    accent: 'Indigo'
  feature:
    tabs: false

nav:
- 数据可视化:
  - FineBI:
    - 5.1 <--> 6.5: Business_Intelligence/FineBI_5.1.md
    - 5.1 <--> 8.0: Business_Intelligence/FineBI_5.1.md
  - IBM Cognos:
    - 10.2.2fp4 <--> C60: Business_Intelligence/IBM_Cognos.md
  - MicroStrategy:
    - 11.1.4 <--> 6.5: Business_Intelligence/MicroStrategy_11.1.4.md
    - 11.1.4 <--> 8.0: Business_Intelligence/MicroStrategy_11.1.4.md
  - Oracle BIEE:
    - 11g <--> C60: Business_Intelligence/Oracle_BIEE.md
    - 11g <--> C70: Business_Intelligence/Oracle_BIEE.md
    - 12c <--> C60: Business_Intelligence/Oracle_BIEE.md
    - 12c <--> C70: Business_Intelligence/Oracle_BIEE.md
    - 12c <--> 6.5: Business_Intelligence/Oracle_BIEE.md
    - 12c <--> 8.0: Business_Intelligence/Oracle_BIEE.md
  - Power BI:
    - 2.75.5649.861 <--> 6.5: Business_Intelligence/PowerBI_2.75.5649.861.md
    - 2.75.5649.861 <--> 8.0: Business_Intelligence/PowerBI_2.75.5649.861.md
  - Qlik Sense:
    - 3.2.4 <--> C70: Business_Intelligence/QlikSense.md
    - 3.2.4 <--> 6.5: Business_Intelligence/QlikSense.md
  - QlikView:
    - 12 <--> C60: Business_Intelligence/QlikView.md
    - 12 <--> C70: Business_Intelligence/QlikView.md
    - 12 <--> C80: Business_Intelligence/QlikView.md
    - 12 <--> 6.5: Business_Intelligence/QlikView.md
    - 12 <--> 8.0: Business_Intelligence/QlikView.md
  - SSRS:
    - 2017 <--> 6.5: Business_Intelligence/SSRS.md
  - SmartBI:
    - 9.5.64075.21175 <--> 8.0: Business_Intelligence/SmartBI.md
  - Tableau:
    - 10.0.0 <--> C50: Business_Intelligence/Tableau.md
    - 10.1.4 <--> C60: Business_Intelligence/Tableau.md
    - 10.3.2 <--> C70: Business_Intelligence/Tableau.md
    - 10.5.0 <--> C80: Business_Intelligence/Tableau.md
    - 10.5.0 <--> 6.5: Business_Intelligence/Tableau.md
    - 10.5.0 <--> 8.0: Business_Intelligence/Tableau.md
- 数据分析:
  - Alteryx:
    - 2018.2.5.48994 <--> C60: Data_Analysis/Alteryx.md
    - 2018.2.5.48994 <--> C80: Data_Analysis/Alteryx.md
    - 2018.2.5.48994 <--> 6.5: Data_Analysis/Alteryx.md
    - 2018.2.5.48994 <--> 8.0: Data_Analysis/Alteryx.md
  - GeoMesa:
    - 2.3.1 <--> 6.5: Data_Analysis/GeoMesa_2.3.1.md
  - Rapidminer Studio:
    - 8.2.001 <--> C80: Data_Analysis/RapidMiner.md
  - SAS:
    - 9.4M3 <--> C60: Data_Analysis/SAS_9.4M3.md
    - 9.4M3 <--> C70: Data_Analysis/SAS_9.4M3.md
    - 9.4M3 <--> C80: Data_Analysis/SAS_9.4M3.md
  - SSAS:
    - 2017 <--> 6.5: Data_Analysis/SSAS.md
  - Splunk:
    - 7.2.4 <--> C80: Data_Analysis/Splunk.md
    - 7.2.4 <--> 6.5: Data_Analysis/Splunk.md
    - 7.2.4 <--> 8.0: Data_Analysis/Splunk.md
  - 永洪一站式大数据分析平台:
    - 7.1 <--> C60: Data_Analysis/永洪一站式大数据分析平台.md
    - 8.7 <--> 8.0: Data_Analysis/永洪一站式大数据分析平台.md
    - 9.2.1 <--> 8.0: Data_Analysis/永洪一站式大数据分析平台_v921.md
- 数据集成:
  - Apache NiFi:
    - 1.7.1 <--> C80: Data_Integration/Apache_NiFi.md
    - 1.9.2 <--> 6.5: Data_Integration/ApacheNifi-1.9.2.md
    - 1.12.0 <--> 8.0: Data_Integration/ApacheNifi-1.9.2.md
  - Confluent:
    - 4.1.0 <--> C80: Data_Integration/Confluent_4_1_0.md
    - 4.1.0 <--> 6.5: Data_Integration/Confluent_4_1_0.md
    - 5.5.0 <--> 8.0: Data_Integration/Confluent_5_5_0.md
  - DataX:
    - 0.1 <--> 6.5: Data_Integration/DataX.md
    - 0.1 <--> 8.0: Data_Integration/DataX.md
  - Denodo Platform:
    - 7.0 <--> C80: Data_Integration/Denodo.md
    - 7.0 <--> 6.5: Data_Integration/Denodo.md
    - 7.0 <--> 8.0: Data_Integration/Denodo.md
  - H2O.ai:
    - 3.24.0.2 <--> 6.5: Data_Integration/H2O.ai.md
    - 3.24.0.2 <--> 8.0: Data_Integration/H2O.ai.md
  - IBM InfoSphere CDC:
    - 11.3.3.1 <--> C50: Data_Integration/IBM_InfoSphere_CDC.md
  - IBM InfoSphere DataStage:
    - 11.3.1.0 <--> C50: Data_Integration/IBM_InfoSphere_DataStage.md
    - 11.5.0.2 <--> C60: Data_Integration/IBM_InfoSphere_DataStage.md
  - Informatica PowerCenter:
    - 10.2.0 <--> C80: Data_Integration/Informatica_PowerCenter.md
    - 10.2.0 <--> 6.5: Data_Integration/Informatica_PowerCenter.md
  - Informatica PowerexChange CDC:
    - 10.2.0 <--> C80: Data_Integration/Informatica_PWX_CDC.md
  - Informatica:
    - 10.0.0 <--> C50: Data_Integration/Informatica_BDM_10.2.2.md
    - 10.0.0 <--> C60: Data_Integration/Informatica_BDM_10.2.2.md
    - 10.0.0 <--> C80: Data_Integration/Informatica_BDM_10.2.2.md
    - 10.0.0 <--> C70: Data_Integration/Informatica_BDM_PushDown.md
    - 10.2.2 <--> 6.5: Data_Integration/Informatica_BDM_10.2.2.md
    - 10.2.2 <--> 8.0: Data_Integration/Informatica_BDM_10.2.2.md
  - Kettle:
    - 6.1 <--> C60: Data_Integration/Kettle_6.1.md
    - 6.1 <--> C70: Data_Integration/Kettle_6.1.md
    - 6.1 <--> C80: Data_Integration/Kettle_6.1.md
    - 6.1 <--> 6.5: Data_Integration/Kettle_6.1.md
    - 6.1 <--> 8.0: Data_Integration/Kettle_6.1.md
  - Knime:
    - 3.6.1 <--> C80: Data_Integration/Knime.md
    - 4.1.0 <--> 6.5: Data_Integration/Knime.md
    - 4.1.0 <--> 8.0: Data_Integration/Knime.md
  - OceanSource:
    - 1.0 <--> C80: Data_Integration/OceanSource.md
  - Oracle GoldenGate:
    - 12.2 <--> C60: Data_Integration/Oracle_GoldenGate.md
    - 12.2 <--> 6.5: Data_Integration/Oracle_GoldenGate.md
    - 12.2 <--> 8.0: Data_Integration/Oracle_GoldenGate.md
    - 12.3 <--> C70: Data_Integration/Oracle_GoldenGate.md
    - 12.3 <--> C80: Data_Integration/Oracle_GoldenGate.md
  - Pentaho EE:
    - 7.1 <--> C70: Data_Integration/Pentaho.md
    - 8.0 <--> C60: Data_Integration/Pentaho.md
  - SharePlex:
    - 9.2.1 <--> C80: Data_Integration/SharePlex.md
    - 9.2.1 <--> 6.5: Data_Integration/SharePlex.md
  - Streamsets:
    - 3.16.1 <--> 6.5: Data_Integration/streamsets_3.16.1.md
    - 3.16.1 <--> 8.0: Data_Integration/streamsets_3.16.1.md
  - Talend:
    - 6.4.1 <--> C80: Data_Integration/Talend_6.4.1.md
    - 6.4.1 <--> 8.0: Data_Integration/Talend_6.4.1.md
    - 7.0.1 <--> C80: Data_Integration/Talend_6.4.1.md
    - 7.2.1 <--> 6.5: Data_Integration/Talend_7.2.1.md
    - 7.2.1 <--> 8.0: Data_Integration/Talend_7.2.1_MRS802.md
  - Tibco BW:
    - 5.13 <--> 6.5: Data_Integration/TIBCO_BusinessWorks.md
  - debezium:
    - 1.0.0 <--> 6.5: Data_Integration/DEBEZIUM.md
    - 1.2.2 <--> 8.0: Data_Integration/DEBEZIUM.md
  - 杭州合众UTL:
    - 5.1 <--> C50: Data_Integration/杭州合众UTL.md
- 数据库:
  - Apache Druid:
    - 0.14.2 <--> C80: Database/apache_druid_0.14.2.md
    - 0.15.1 <--> C80: Database/apache_druid_0.15.1.md
  - OpenTSDB:
    - 2.4.0 <--> 6.5: Database/OpenTSDB_2.4.0.md
    - 2.4.0 <--> 8.0: Database/OpenTSDB_2.4.0.md
  - SAP VORA:
    - 2.0 <--> C70: Database/SAP_VORA.md
    - 2.1 <--> C70: Database/SAP_VORA.md
  - 杭州合众UDB:
    - 6.1 <--> C50: Database/杭州合众UDB.md
- 集成开发环境:
  - Anaconda:
    - 2-2019.03-Linux-x86_64 <--> 6.5: Development/Anaconda.md
    - 2-2019.03-Linux-x86_64 <--> 8.0: Development/Anaconda.md
  - DBeaver:
    - 4.0.8 <--> C60: Development/DBeaver_4.2.1.md
    - 4.2.1 <--> C70: Development/DBeaver_4.2.1.md
    - 6.1.4 <--> 6.5: Development/DBeaver_6.1.4.md
    - 6.3.4 <--> 6.5: Development/DBeaver_6.3.4.md
    - 6.3.4 <--> 8.0: Development/DBeaver_6.3.4.md
  - DbVisualizer:
    - 10.0.1 <--> C70: Development/DbVisualizer_10.0.1.md
    - 10.0.21 <--> 6.5: Development/DbVisualizer_10.0.21.md
    - 10.0.21 <--> 8.0: Development/DbVisualizer_10.0.21.md
    - 9.5.7 <--> C60: Development/DbVisualizer_10.0.1.md
  - HUE:
    - 4.0.1 <--> C70: Development/HUE.md
  - Jupyter Notebook:
    - 2.4.4.0 <--> C70: Development/Jupyter_Notebook.md
    - 2.7.16 <--> C80: Development/JupyterNotebook.md
    - 2.7.16 <--> 6.5: Development/JupyterNotebook.md
  - JupyterHub:
    - 1.0.0 <--> C80: Development/JupyterHub.md
    - 1.0.0 <--> 8.0: Development/JupyterHub.md
  - RStudio:
    - 3.4.1 <--> C60: Development/RStudio.md
    - 3.4.1 <--> C70: Development/RStudio.md
    - 3.4.1 <--> 8.0: Development/RStudio.md
  - Squirrel:
    - 3.7.1 <--> C60: Development/Squirrel_3.8.0.md
    - 3.8.0 <--> C70: Development/Squirrel_3.8.0.md
    - 3.9.1 <--> 6.5: Development/Squirrel_3.9.1.md
    - 3.9.1 <--> 8.0: Development/Squirrel_3.9.1.md
  - Zeppelin:
    - 0.7.2 <--> C60: Development/Zeppelin_0.7.2.md
    - 0.7.3 <--> C70: Development/Zeppelin_0.7.3.md
    - 0.7.3 <--> C80: Development/Zeppelin_0.7.3.md
    - 0.8.0 <--> C80: Development/Zeppelin_0.8.0.md
    - 0.8.1 <--> 6.5: Development/Zeppelin_0.8.1.md
    - 0.9.0 <--> 8.0: Development/Zeppelin_0.8.1.md
- 其他:
  - Apache Airflow:
    - 1.10.6 <--> 6.5: Other/Airflow.md
    - 1.10.6 <--> 8.0: Other/Airflow.md
  - Apache Livy:
    - 0.5.0 <--> C80: Other/Apache_Livy_0_5_0.md
    - 0.6.0 <--> 6.5: Other/Apache_Livy_0_6_0.md
    - 0.7.0 <--> 8.0: Other/Apache_Livy_0_6_0.md
  - GIS Tools for Hadoop:
    - 1.0 <--> C60: Other/GIS_Tools.md
  - IBM WAS:
    - 8.5.5.9 <--> C50: Other/IBM_WAS.md
  - Kibana:
    - 6.1.3 <--> C80: Other/Elasticsearch_Related.md
    - 6.1.3 <--> 8.0: Other/Elasticsearch_Related.md
  - Logstash:
    - 6.4.2 <--> C80: Other/Elasticsearch_Related.md
    - 6.7.1 <--> 6.5: Other/Logstash.md
    - 6.7.1 <--> 8.0: Other/Logstash.md
  - NeoKylin:
    - 6.9 <--> C70: Other/NeoKylin.md
    - 7.2 <--> C70: Other/NeoKylin.md
  - Tensorflow:
    - 1.15.0 <--> 6.5: Other/Tensorflow.md
    - 2.1.0 <--> 6.5: Other/Tensorflow.md
    - 1.15.0 <--> 8.0: Other/Tensorflow.md
    - 2.1.0 <--> 8.0: Other/Tensorflow.md
  - elasticsearch-head:
    - 1.0 <--> C80: Other/Elasticsearch_Related.md
    - 1.0 <--> 8.0: Other/Elasticsearch_Related.md
  - filebeat:
    - 6.5.1 <--> C80: Other/Elasticsearch_Related.md
    - 6.5.1 <--> 8.0: Other/Elasticsearch_Related.md
  - librdkafka:
    - 1.0 <--> 6.5: Other/librdkafka.md
  - 生态对接常见问题总结:
    - 1.0 <--> 6.5: Other/对接问题总结1.0.md
  - MRS使用负载均衡实现HA适配说明书:
    - 1.0 <--> 8.0: Other/MRS使用负载均衡实现HA适配说明书.md
  - MRS使用负载均衡实现HA：基于微软云的适配代码与安装说明书:
    - 1.0 <--> 8.0: Other/MRS使用负载均衡实现HA：基于微软云的适配代码与安装说明书.md
- SQL分析:
  - Apache Drill:
    - 1.15.0 <--> 6.5: SQL_Analytics/ApacheDrill_1.15.0toHD651.md
    - 1.15.0 <--> C80: SQL_Analytics/Apache_Drill_1.15.0.md
    - 1.17.0 <--> 6.5: SQL_Analytics/ApacheDrillto17HD.md
    - 1.17.0 <--> 8.0: SQL_Analytics/ApacheDrillto17HD.md
  - Apache Kylin:
    - 1.6.0 <--> C60: SQL_Analytics/Apache_Kylin_1.6.0.md
    - 2.1.0 <--> C70: SQL_Analytics/Apache_Kylin_2.1.0.md
    - 2.3.1 <--> C80: SQL_Analytics/Apache_Kylin_2.3.1.md
    - 2.6.1 <--> 6.5: SQL_Analytics/Apache_Kylin_2.6.1.md
    - 3.0.1 <--> 6.5: SQL_Analytics/ApacheKylin3.0.1.md
    - 3.1.1 <--> 8.0: SQL_Analytics/Apache_Kylin3.1.1-MRS.md
  - Kyligence Analytics Platform:
    - 2.2 <--> C60: SQL_Analytics/Kyligence.md
    - 2.3 <--> C60: SQL_Analytics/Kyligence.md
    - 2.4 <--> C70: SQL_Analytics/Kyligence.md
    - 2.5 <--> C70: SQL_Analytics/Kyligence.md
    - 3.0 <--> C80: SQL_Analytics/Kyligence.md
  - Presto:
    - 0.155 <--> C60: SQL_Analytics/Presto_0.155.md
    - 0.184 <--> C70: SQL_Analytics/Presto_0.184.md
    - 0.196 <--> C80: SQL_Analytics/Presto_0.184.md
    - 0.210 <--> C80: SQL_Analytics/Presto_0.210.md
    - 0.210 <--> 6.5: SQL_Analytics/Presto_0.210.md
    - 0.210 <--> 8.0: SQL_Analytics/Presto_0.210.md

extra:
  social:
    - type: github
      link: https://github.com/fusioninsight
  search:
    language: 'jp'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra_javascript:
  - 'js/jq.js'
  - 'js/extra.js'
  - 'js/baidu-tongji.js'

extra_css:
  - 'css/extra.css'
